- name: "Build Status"
  shield: "github/actions/workflow/status/chirag127/ClerkFlow-Secure-Auth-Browser-Extension/ci.yml?style=flat-square"
  alt: "GitHub Actions Build Status"
- name: "Code Coverage"
  shield: "codecov/c/github/chirag127/ClerkFlow-Secure-Auth-Browser-Extension?style=flat-square"
  alt: "Code Coverage"
- name: "TypeScript"
  shield: "badge/Language-TypeScript-3178C6?style=flat-square"
  alt: "TypeScript"
- name: "Frameworks"
  shield: "badge/Frameworks-React%20%7C%20Vite-F15A29?style=flat-square"
  alt: "Frameworks"
- name: "License"
  shield: "badge/License-CC%20BY--NC%204.0-blue?style=flat-square"
  alt: "License"
- name: "GitHub Stars"
  shield: "github/stars/chirag127/ClerkFlow-Secure-Auth-Browser-Extension?style=flat-square"
  alt: "GitHub Stars"
